// Generates AVIF / WebP / JPEG derivatives from the approved originals.
// Originals are read-only inputs; nothing in assets/originals is written.
// Output: public/images/<id>-<width>.<ext> and src/generated/imageAssets.ts
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const root = path.resolve(import.meta.dirname, '..');
const config = JSON.parse(await readFile(path.join(root, 'assets/image-sources.json'), 'utf8'));
const outDir = path.join(root, config.outputDir);
await mkdir(outDir, { recursive: true });

// Find the bounding box of non-pure-white content. A row/column is treated as
// padding only if every pixel in it is >= 254 on all channels.
async function contentBox(file) {
  const { data, info } = await sharp(file).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;
  const isWhite = (x, y) => {
    const i = (y * width + x) * channels;
    return data[i] >= 254 && data[i + 1] >= 254 && data[i + 2] >= 254;
  };
  const rowWhite = (y) => { for (let x = 0; x < width; x++) if (!isWhite(x, y)) return false; return true; };
  const colWhite = (x, top, bottom) => { for (let y = top; y < bottom; y++) if (!isWhite(x, y)) return false; return true; };
  let top = 0; while (top < height && rowWhite(top)) top++;
  let bottom = height; while (bottom > top && rowWhite(bottom - 1)) bottom--;
  let left = 0; while (left < width && colWhite(left, top, bottom)) left++;
  let right = width; while (right > left && colWhite(right - 1, top, bottom)) right--;
  // Inset by 2px to drop anti-aliased edge pixels of the letterbox.
  const inset = top > 0 || left > 0 || bottom < height || right < width ? 2 : 0;
  return { left: left + inset, top: top + inset, width: right - left - inset * 2, height: bottom - top - inset * 2 };
}

const manifest = {};
for (const asset of config.assets) {
  const src = path.join(root, asset.source);
  if (!existsSync(src)) throw new Error(`Missing original: ${asset.source}`);
  const meta = await sharp(src).metadata();
  const box = asset.trimWhiteBorder
    ? await contentBox(src)
    : { left: 0, top: 0, width: meta.width, height: meta.height };
  const widths = config.widths.filter((w) => w <= box.width);
  if (!widths.includes(box.width) && box.width < config.widths.at(-1)) widths.push(box.width);
  for (const w of widths) {
    const base = sharp(src).extract(box).resize({ width: w, withoutEnlargement: true });
    const stem = path.join(outDir, `${asset.id}-${w}`);
    await Promise.all([
      base.clone().avif({ quality: 52, effort: 6 }).toFile(`${stem}.avif`),
      base.clone().webp({ quality: 78 }).toFile(`${stem}.webp`),
      base.clone().jpeg({ quality: 80, mozjpeg: true }).toFile(`${stem}.jpg`),
    ]);
  }
  manifest[asset.id] = {
    id: asset.id,
    source: asset.source,
    width: box.width,
    height: box.height,
    widths,
    trimmed: asset.trimWhiteBorder ? box : null,
  };
  console.log(`${asset.id}: ${box.width}x${box.height} → ${widths.join(', ')}`);
}

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export const imageAssets = ${JSON.stringify(manifest, null, 2)} as const;

export type ImageAssetId = keyof typeof imageAssets;
`;
await writeFile(path.join(root, 'src/generated/imageAssets.ts'), ts);
